logging:
  level:
    root: info

spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
      enabled: true

  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${db.url}
      username: ${db.username}
      password: ${db.password}
      minimum-idle: 5
      maximum-pool-size: 100
      max-lifetime: 28800000
      keepalive-time: 60000
      idle-timeout: 60000
      read-only: true

    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${db.url}
      username: ${db.username}
      password: ${db.password}
      minimum-idle: 5
      maximum-pool-size: 100
      max-lifetime: 28800000
      keepalive-time: 60000
      idle-timeout: 60000

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop

gorilla:
  api: ${gorilla.api}
  code: ${gorilla.code}
  name: ${gorilla.name}
  id: ${gorilla.id}
  pass: ${gorilla.pass}
  key: ${gorilla.key}

#  jpa:
#    show-sql: true
##    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: create-drop
#    open-in-view: false
#
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:mem:batch;DB_CLOSE_DELAY=-1
#    driver-class-name: org.h2.Driver
#    username: kuku
#    password:

