logging:
  level:
    root: info

spring:
  profiles:
    active: local

  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:batch
    driver-class-name: org.h2.Driver
    username: kuku
    password:
