spring:
  batch:

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:batch;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: kuku
      password:
      driver-class-name: org.h2.Driver