spring:
  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${db.url}
      username: ${db.username}
      password: ${db.password}
      minimum-idle: 5
      maximum-pool-size: 100
      max-lifetime: 28800000
      keepalive-time: 60000
      idle-timeout: 60000
      read-only: true

    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${db.url}
      username: ${db.username}
      password: ${db.password}
      minimum-idle: 5
      maximum-pool-size: 100
      max-lifetime: 28800000
      keepalive-time: 60000
      idle-timeout: 60000

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
    sql-migration-suffixes: .sql
    locations: classpath:/db/migration
    baseline-version: 0

  data:
    redis:
      port: 6379
      host: localhost

logging.level:
  org.hibernate.SQL: debug
