spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:core;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: core
    password:

  jpa:
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: true

  h2:
    console:
      enabled: true
      path: /h2-console